services:
    metamodels.attribute_alias.factory:
        class: MetaModels\AttributeAliasBundle\Attribute\AttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
        tags:
          - { name: metamodels.attribute_factory }

    metamodels.attribute_alias.backend_listener.get_options:
        class: MetaModels\AttributeAliasBundle\EventListener\GetOptionsListener
        arguments:
          - '@cca.dc-general.scope-matcher'
          - '@metamodels.factory'
        tags:
          - { name: kernel.event_listener, event: 'men-at-work.multi-column-wizard-bundle.get-options', method: getOptions }
