services:
    MetaModels\AttributeAliasBundle\Attribute\AttributeTypeFactory:
        class:
        arguments:
            - '@database_connection'
            - '@metamodels.table_manipulator'
            - '@event_dispatcher'
            - '@contao.slug'
        tags:
          - { name: metamodels.attribute_factory }

    MetaModels\AttributeAliasBundle\EventListener\GetOptionsListener:
        class:
        arguments:
          - '@cca.dc-general.scope-matcher'
          - '@metamodels.factory'
        tags:
          - { name: kernel.event_listener, event: 'men-at-work.multi-column-wizard-bundle.get-options', method: getOptions }

    MetaModels\AttributeAliasBundle\Migration\AllowNullMigration:
        arguments:
            - '@database_connection'
        tags:
            - name: contao.migration

    MetaModels\AttributeAliasBundle\Schema\DoctrineSchemaGenerator:
      tags:
        - { name: 'metamodels.schema-generator.doctrine' }
